
import "./globals.css";
import  {Providers} from '../redux/Providers';
import {Navbar} from '../components/Navbar.js'

//const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function RootLayout({
  children,
}) {
  return (
    <html lang="en">
      <Providers>

      <body>
        
              <div id='containerMain' >
                <Navbar />
                <div className={"containerPage"} >
                  {children}
                </div>
                {/* <Footer/> */}
              </div>
           
      </body>
      </Providers>
    </html>
  );
}

export default RootLayout


