
import "./globals.css";
import  {Providers} from '../redux/Providers';

//const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function RootLayout({
  children,
}) {
  return (
    <html lang="en">
      <Providers>

      <body>
        {children}
      </body>
      </Providers>
    </html>
  );
}

export default RootLayout